### ISSUE TITLE
[Feature request] Create command only for downloading dependencies 

### ISSUE THREAD

**Issue by marciopd** [markgardner/node-flywaydb#11]
Hello Mark, congrats for the awesome project!

When using this library in a Kubernetes environment, where pods can be deleted and created all the time, it would be nice to not download Flyway's command line tool every time starting a new pod.

My suggestion would be adding a command `prepare-flyway-cli` or so, that would only download the library's dependencies. This could be used during the docker image creation process, instead of when starting the containers (node process).

Please give me your thoughts on this.

Best regards!

**Comment by marciopd** [comment]
As far I studied the code, the proposed command would execute `download.ensureArtifacts` without triggering a command execution to flyway.

**Comment by markgardner** [comment]
Hey Márcio,

I'm thinking this could be done without maintaining another project.

Right now all you need to do is execute a command. IE adding a postinstall to your package.json.
`{
    "scripts": {
        "postinstall": "flyway -c flywayconfig.js info"
   }
}`

This could cause your install to fail if the connection to your database fails.

Would this solution solve the problem your facing?

**Comment by marciopd** [comment]
Hi Marc, that could maybe work.

I noticed there's some kind of expiration time check regarding `fly-way-commandline`'s download. Would it be possible to not download again at all? 

Something that might be an option too is being able to provide in `flywayconfig.js` the path to a local `fly-way-commandline` download file. In that way it's guaranteed that  `node-flywaydb` would always have a command line tool locally, without needing to hit the network.

**Comment by markgardner** [comment]
yeah that makes sense.

The cached download expiration is useful to download new updates without having to clear the node_modules folder. Adding a configuration property of `cacheExpiration` to allow users to set the life of the cached downloads. Setting the value to a negative value would make it infinite and setting it to zero would basically remove the cache all together.

I like the idea of being able to specify the download/extract directories. That does open up a potential problem with write permissions (hidden benefit of writing to the node_modules directory by default). But that can be a problem that can be solved by the user.

PR's are welcome, otherwise I'll probably get to this next week.

**Comment by marciopd** [comment]
Hi Marc, If you didn't start,  I'll try to work on something today.

**Comment by markgardner** [comment]
I haven’t yet.

**Comment by marciopd** [comment]
First PR: [download expiration time config](https://github.com/markgardner/node-flywaydb/pull/12)

Another one coming this week I hope.

**Comment by markgardner** [comment]
I just pushed a release with your changes and a chance for a configurable download folder. Let me know if they solve your use case.

**Comment by marciopd** [comment]
Just tested and it works well. Thanks, Mark!

**Comment by markgardner** [comment]
Good to hear, thanks for the help
